### ISSUE TITLE
Disable lint checks for translation

### ISSUE THREAD

**Issue by krt16s** [Zyg0te/Locker#10]
Building the app errors with:

````
/home/krt/src/fdroiddata/build/net.zygotelabs.locker/android/app/src/main/res/values-zh-rCN/strings.xml:37:1: Error: Content is not allowed in trailing section.
:app:mergeReleaseResources FAILED
````

to fix this, I applied the workaround `android { lintOptions { disable 'MissingTranslation' } }` to the app/build.gradle file. However, this issue should be handled in upstream, either by actually fixing the issue or by applyting this workaround yourself -- you know better when/if this is ok for a release or not.

**Comment by Zyg0te** [comment]
Are you sure you have the latest version of the translation file? The initial Chinese translation had some meta data added to the end there that causes issues when compiling. I fixed this a few commits ago.

**Comment by krt16s** [comment]
This has indeed been dealt with in 1.07, sorry for the noise :/
