### ISSUE TITLE
Working with 3rd party screen locker

### ISSUE THREAD

**Issue by gmaddry** [Zyg0te/Locker#13]
I am using C Locker for my screen locker. Your description, "Depending on what lock screen application you are using the user will be presented with warning messages when the number of remaining attempts is 4 or less",  in Play Store implies that you work with 3rd party screen lockers however when I open your app in says Not protected. Do you work with 3rd party screen lockers such as C Locker?

**Comment by Zyg0te** [comment]
Hi there. 

That section of the README simply states that its the lock screen app that determines how to warn the user before you run out of the unlock attempts. 

Locker works regardless* of what lock screen app you're using. Locker will say that your device is not protected until you enable and activate the protection from within Locker. 

Hope that makes sense.

* If you're using a lock screen that doesn't properly report failed unlock attempts I suppose Locker would fail to function properly.

**Comment by gmaddry** [comment]
Thanks I think I will make a backup and test.
