### ISSUE TITLE
Hide icon app from launcher

### ISSUE THREAD

**Issue by 876974** [Zyg0te/Locker#20]
Hidden version
option to hide icon app from launcher and show app in secret phone number (dial 562237 locker or set your nuber)

**Comment by Zyg0te** [comment]
I'll look into this. However, the purpose of Locker is to make it significantly more difficult to brute force the device unlock code. If the phone is locked they wont see the app launcher. So whats the use case here?

**Comment by 876974** [comment]
If initially the phone will fall into the hands of man with the unlocked screen, it will already be aware of the presence of the installed application, which will be hidden from prying eyes.

**Comment by kstefanini** [comment]
You have many ways to hide app icon from launcher, maybe it's not a Locker's core feature.

**Comment by Zyg0te** [comment]
I would tend to agree with @kstefanini. If you want to hide Locker icon from the app launcher, then the easiest way is to use a third party launcher that includes this capability.
