### ISSUE TITLE
No warning message

### ISSUE THREAD

**Issue by ajay340** [Zyg0te/Locker#22]
I have the app enabled but it gives no warnings after a failed input.

**Comment by Zyg0te** [comment]
Hi there. Depending on your device, ROM and lock screen app, you'll only start to see warning messages when you have 5 attempts remaining or less. The warning usually takes the form of a text label that's shown statically on the lock screen indicating the number of attempts you have left. Are you sure you're not seeing any of this?

Cheers

**Comment by ajay340** [comment]
Hi I'm on a Galaxy S6 using my fingerprints as my lockscreen with no custom ROM. I still don't see it when its down to 5 countdowns.

**Comment by Zyg0te** [comment]
Unfortunately the Device Administration API does not support fingerprint unlocks. This is unfortunately nothing Locker can do anything about.

**Comment by Zyg0te** [comment]
I'll close this issue. Feel free to add a comment if you feel like the issue should remain open. 

Cheers!

**Comment by michal-ruzicka** [comment]
So fingerprint unlock failed attempts does not count to unlock attempts and will not trigger the wipe action? Even on Nexus 5X/6P with Android 6 native fingerprint API?

**Comment by Zyg0te** [comment]
Correct. This is simply because Android does not count a failed fingerprint unlock attempt as an actual failed unlock attempt. The Device Administration API is simply not integrated with the fingerprint component and I have not been able to find a workaround.

**Comment by michal-ruzicka** [comment]
It is really a pity. Such a not-very-secure method of unlocking as fingerprint scan would be the hot candidate for this autowipe protection. Hopefully some API will be added in the future.

Aren't you aware at least of some API allowing to set hard limit of fingerprint scan before this method is locked down and the user's set backup method _have to_ be used no matter how long from the last failed finger print scan? It would be possibly sufficient protection.

The current behaviour of the clean Google Android 6.0.1 on Nexus device is to force backup method (PIN/password/patter) after ~10 failed fingerprint scans but after quite a short time (30 seconds?) another batch of fingerprint attempts is allowed. Force change of  this behaviour to, for example, up to 3 fingerprint scans and consequent forced requirement of a successful use of the backup unlocking method would be very useful and with strong password set as the backup method relatively secure.

**Comment by ajay340** [comment]
This works on Android 6.0

**Comment by michal-ruzicka** [comment]
@ajay340 What exactly do you meat by ‘this’? The wipe functionality or forced requirement of the backup method (and on what conditions)? Thanks.

**Comment by ajay340** [comment]
I'm not sure about the wipe function but the warning message comes up.

**Comment by michal-ruzicka** [comment]
@ajay340 OK, thanks for the clarification. I think the availability of the warning message has more to do with the used lock screen application. I would expect the stock Android lock screen, especially on the Nexus devices with pure Android by Google, to fork fine.
