### ISSUE TITLE
Consider adding option to force shutdown instead of wipe

### ISSUE THREAD

**Issue by fowlslegs** [Zyg0te/Locker#25]
Would you consider adding the option to simply shutdown the phone after a specified failed number of lockscreen attempts? For those who use disk encryption w/ a strong password and a weak lockscreen password (see https://github.com/nelenkov/cryptfs-password-manager for a tool that let's you set these passwords independently) this seems like a safer option than a wipe and also seems more comfortable--I don't have to worry about my data being wiped and can also verify myself and have confidence the forced shutdown mechanism works on my device!

It would also be nice if one could disable remaining pin attempt warnings in this mode.

Lastly and obviously, the failed pin attempt count would have to reset after reboot in this mode.

**Comment by Zyg0te** [comment]
Thanks for the feedback.

The shutdown-option has been discussed [here](https://github.com/Zyg0te/Locker/issues/12). It might sound trivial to implement but regular third party apps do not seem to have the ability to shut down the device at all. 

Best regards

**Comment by fowlslegs** [comment]
Closing in favor of #12.
