### ISSUE TITLE
Add test mode

### ISSUE THREAD

**Issue by michal-ruzicka** [Zyg0te/Locker#26]
A test mode could be useful to test the proper function of the app. If switched to the test mode the app should behaviour exactly the same way as in the regular mode. However, if wipe action is should be triggered the app would only show dialogue (or send email, show notification...) informing the user the wipe action would be triggered as of now in the regular mode.

**Comment by Zyg0te** [comment]
Great idea!

**Comment by michal-ruzicka** [comment]
You are great, such a quick response. Thank you very much!

**Comment by Zyg0te** [comment]
Thanks! Update published to Google Play now so it will be available in a few hours I reckon.

**Comment by fathermaurer** [comment]
Available and installed. Great addition - thank you.
