### ISSUE TITLE
Rename app?

### ISSUE THREAD

**Issue by Gaff** [Zyg0te/Locker#6]
There are dozens of apps called "Locker", this app isn't even in the top 10: https://play.google.com/store/search?q=locker&hl=en_GB

This is a shame because it's a great app! Perhaps if it had a more distinctive name it would be easier for people to find?

Having said that I've no idea what a good name would be! Apple call this feature "Erase Data": http://ioshacker.com/how-to/enable-erase-data-option-delete-data-10-failed-passcode-attempts but that's a bit dull too.

I'll have a think :) - thanks for all the great work anyway!!

**Comment by Zyg0te** [comment]
I completely agree. A name change could be a good idea but I honestly have
no suggestions for a better name.

But thanks for the feedback!

On Friday, 11 March 2016, Matthew Shaylor <notifications@github.com> wrote:

> There are dozens of apps called "Locker", this app isn't even in the top
> 10: https://play.google.com/store/search?q=locker&hl=en_GB
>
> This is a shame because it's a great app! Perhaps if it had a more
> distinctive name it would be easier for people to find?
>
> Having said that I've no idea what a good name would be! Apple call this
> feature "Erase Data":
> http://ioshacker.com/how-to/enable-erase-data-option-delete-data-10-failed-passcode-attempts
> but that's a bit dull too.
>
> I'll have a think :) - thanks for all the great work anyway!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Zyg0te/Locker/issues/6>.
>


-- 
Edvard;
