### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by anarcat** [Zyg0te/Locker#9]
The 1.0.6 release publish on Google Play isn't clearly identified here. I am *guessing* it could be 44d8dbdd8a31e834b5d0b331661d0efa39b41b74 because that is when the version number was changed, but there were also other bugfixes performed a few seconds later...

which one is the release?

i am trying to add this to f-droid, and it would be really helpful to see those tags...

thanks!

**Comment by Zyg0te** [comment]
Thanks for the feedback. Ill sort out tags asap. Its totally just me being sloppy. A minor update should be out tomorrow so Ill make sure to tag it properly then as well.

Cheers!

**Comment by Zyg0te** [comment]
Added tags for the latest version and for version 1.0.6. Let me know if there is anything missing. 

Cheers.

**Comment by anarcat** [comment]
awesome, thanks!

**Comment by anarcat** [comment]
and, and for the record, the f-droid application is here: https://gitlab.com/fdroid/fdroiddata/merge_requests/1301

still WIP because I can't figure out how to build the thing... i am new at that Android SDK stuff and it's not liking me.
